[package]
name = "neo_granseal"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
wgpu = {version = "0.14.0" , features = ["webgl"]}
pollster = "0.2.5"
bytemuck = {version = "1.12.2", features = ["extern_crate_alloc","derive"]}
image = "0.24.4"
log = "0.4.17"
env_logger = "0.9.1"
rand = "0.8.5"
rand_xorshift = "0.3.0"
num-traits = "0.2.15"
cgmath = "0.18.0"
rusttype = {version = "0.9.3"}

[lib]

[[example]]
name = "pixels"
test = false

[[example]]
name = "other"
test = false

[[example]]
name = "shapes"
test = false

[[example]]
name = "simplest_box"
test = false